config/routes.rb
Rails.application.routes.draw do
  get 'notes/new'
  root 'notes#index'

  resources :notes
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3 }
  validates :text, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)

    if @note.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    @note = Note.find(params[:id])

    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end

  def edit
    @note = Note.find(params[:id])
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    redirect_to notes_path
  end

  def index
    @notes = Note.all
  end

  def show
    @note = Note.find(params[:id])
  end

  private

  def note_params
    params.require(:note).permit(:title, :date, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      redirect_to @user
      flash[:success] = 'User created successfully'
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <%= yield(:title) %>
  </title>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="header">
    <% if signed_in? -%>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path %>
    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>

app/views/notes/_form.html.erb
<%= form_with model: @note, local: true do |form| %>

    <% if @note.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@note.errors.count, 'error') %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @note.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>

    <p>
      <%= form.label :date_of_event %><br>
      <%= form.date_select :date %>
    </p>

    <p>
      <%= form.submit %>
    </p>

    <%= link_to 'Back', root_path %>
<% end %>

app/views/notes/create.html.erb
<h1>Notes#create</h1>
<p>Find me in app/views/notes/create.html.erb</p>

app/views/notes/destroy.html.erb
<h1>Notes#destroy</h1>
<p>Find me in app/views/notes/destroy.html.erb</p>

app/views/notes/edit.html.erb
<% provide(:title, 'Edit note') %>

<%= render 'form' %>

app/views/notes/index.html.erb
<% provide(:title, 'List of notes') %>

<h1>List of travellers notes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Date</th>
    <th colspan="3"></th>
  </tr>

  <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.text %></td>
        <td><%= note.date %></td>
        <td><%= link_to 'Show', note_path(note) %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Delete', note_path(note),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<%= link_to 'Add new note about your journey', new_note_path %>

app/views/notes/new.html.erb
<% provide(:title, 'Add new note') %>

<%= render 'form' %>

app/views/notes/show.html.erb
<% provide(:title, 'Travelling note') %>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @note.text %>
</p>

<p>
  <strong>Date</strong>
  <%= @note.date %>
</p>

<%= link_to 'Back', notes_path %>

app/views/notes/update.html.erb
<h1>Notes#update</h1>
<p>Find me in app/views/notes/update.html.erb</p>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>

  <%= link_to 'Back', root_path %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>